name: Scheduler Job 2

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  sched-job-0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Lock Sched
        run: |
          git config --local user.email "violet.dev.master@gmail.com"
          git config --local user.name "violet-dev"
          git config --global pull.rebase false
          git pull
          python3 sched-lock.py 2
          git add workspace/lock-2
          git commit -m "lock job 2"
          git pull
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          branch: 'master'
          github_token: $ 
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Download
        run: | 
          pip3 install easyocr
          chmod 777 hdownloader-bin
      - name: A
        run: |
          python3 do-ocr.py 2
      # - name: Upload
      #   uses: actions/upload-artifact@master
      #   with:
      #     name: test-test
      #     path: a.txt
      #     env-url: UPLOADURL
      # - name: Upload S3
      #   uses: shallwefootball/s3-upload-action@master
      #   with:
      #     aws_key_id: ${{ secrets.AWS_KEY_ID }}
      #     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
      #     aws_bucket: ${{ secrets.AWS_BUCKET }}
      #     source_dir: ${{ env.CURRENTID }}.txt
      - name: Update History
        run: |
          git pull
          python3 update-job.py 2 "${{ env.UPLOADURL }}"
          python3 sched-unlock.py 2
      - name: Revision
        run: |
          git add workspace/lock-2
          git add workspace/current_job2
          git add workspace/history-2.txt
          git add result/
          git add .github/
          git commit -m "update job 2"
          git pull
      - name: Push
        id: trypush
        uses: ad-m/github-push-action@master
        with:
          branch: 'master'
          github_token: $
      - name: Fail Safe Pull
        if: ${{ failure() && steps.trypush.outcome == 'failure' }}
        run: git pull
      - name: Fail Safe 1
        id: trypushfs1
        if: ${{ failure() && steps.trypush.outcome == 'failure' }}
        uses: ad-m/github-push-action@master
        with:
          branch: 'master'
          github_token: $ 
      - name: Fail Safe Pull
        if: ${{ failure() && steps.trypushfs1.outcome == 'failure' }}
        run: git pull
      - name: Fail Safe 2
        id: trypushfs2
        if: ${{ failure() && steps.trypushfs1.outcome == 'failure' }}
        uses: ad-m/github-push-action@master
        with:
          branch: 'master'
          github_token: $ 
      - name: Fail Safe Pull
        if: ${{ failure() && steps.trypushfs2.outcome == 'failure' }}
        run: git pull
      - name: Fail Safe 3
        id: trypushfs3
        if: ${{ failure() && steps.trypushfs2.outcome == 'failure' }}
        uses: ad-m/github-push-action@master
        with:
          branch: 'master'
          github_token: $ 
      - name: Fail Safe Pull
        if: ${{ failure() && steps.trypushfs3.outcome == 'failure' }}
        run: git pull
      - name: Fail Safe 4
        id: trypushfs4
        if: ${{ failure() && steps.trypushfs3.outcome == 'failure' }}
        uses: ad-m/github-push-action@master
        with:
          branch: 'master'
          github_token: $ 
      - name: Fail Safe Pull
        if: ${{ failure() && steps.trypushfs4.outcome == 'failure' }}
        run: git pull
      - name: Fail Safe 5
        if: ${{ failure() && steps.trypushfs4.outcome == 'failure' }}
        uses: ad-m/github-push-action@master
        with:
          branch: 'master'
          github_token: $ 

