name: Update README 

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  sched-job-0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Revision
        run: |
          git config --local user.email "violet.dev.master@gmail.com"
          git config --local user.name "violet-dev"
          git config --global pull.rebase false
          git pull
          python3 update-state.py
          git add README.md
          git commit -m "update readme"
          git pull
      - name: Push
        id: trypush
        uses: ad-m/github-push-action@master
        with:
          branch: 'master'
          github_token: $
      - name: Fail Safe Pull
        if: ${{ failure() && steps.trypush.outcome == 'failure' }}
        run: git pull
      - name: Fail Safe 1
        id: trypushfs1
        if: ${{ failure() && steps.trypush.outcome == 'failure' }}
        uses: ad-m/github-push-action@master
        with:
          branch: 'master'
          github_token: $ 
      - name: Fail Safe Pull
        if: ${{ failure() && steps.trypushfs1.outcome == 'failure' }}
        run: git pull
      - name: Fail Safe 2
        id: trypushfs2
        if: ${{ failure() && steps.trypushfs1.outcome == 'failure' }}
        uses: ad-m/github-push-action@master
        with:
          branch: 'master'
          github_token: $ 
      - name: Fail Safe Pull
        if: ${{ failure() && steps.trypushfs2.outcome == 'failure' }}
        run: git pull
      - name: Fail Safe 3
        id: trypushfs3
        if: ${{ failure() && steps.trypushfs2.outcome == 'failure' }}
        uses: ad-m/github-push-action@master
        with:
          branch: 'master'
          github_token: $ 
      - name: Fail Safe Pull
        if: ${{ failure() && steps.trypushfs3.outcome == 'failure' }}
        run: git pull
      - name: Fail Safe 4
        id: trypushfs4
        if: ${{ failure() && steps.trypushfs3.outcome == 'failure' }}
        uses: ad-m/github-push-action@master
        with:
          branch: 'master'
          github_token: $ 
      - name: Fail Safe Pull
        if: ${{ failure() && steps.trypushfs4.outcome == 'failure' }}
        run: git pull
      - name: Fail Safe 5
        if: ${{ failure() && steps.trypushfs4.outcome == 'failure' }}
        uses: ad-m/github-push-action@master
        with:
          branch: 'master'
          github_token: $ 

